/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppValidacaoRouteImport } from './routes/_app.validacao'
import { Route as AppRiscosOlaRouteImport } from './routes/_app.riscos-ola'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppQualidadeDadosRouteImport } from './routes/_app.qualidade-dados'
import { Route as AppProblemasRouteImport } from './routes/_app.problemas'
import { Route as AppPrevisoesRouteImport } from './routes/_app.previsoes'
import { Route as AppMudancasRouteImport } from './routes/_app.mudancas'
import { Route as AppLinhagemDadosRouteImport } from './routes/_app.linhagem-dados'
import { Route as AppIncidentesRouteImport } from './routes/_app.incidentes'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDadosRouteImport } from './routes/_app.dados'
import { Route as AppCorrecoesRouteImport } from './routes/_app.correcoes'
import { Route as AppConhecimentoRouteImport } from './routes/_app.conhecimento'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppArquiteturaRouteImport } from './routes/_app.arquitetura'
import { Route as AppAlertasRouteImport } from './routes/_app.alertas'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppValidacaoRoute = AppValidacaoRouteImport.update({
  id: '/validacao',
  path: '/validacao',
  getParentRoute: () => AppRoute,
} as any)
const AppRiscosOlaRoute = AppRiscosOlaRouteImport.update({
  id: '/riscos-ola',
  path: '/riscos-ola',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppQualidadeDadosRoute = AppQualidadeDadosRouteImport.update({
  id: '/qualidade-dados',
  path: '/qualidade-dados',
  getParentRoute: () => AppRoute,
} as any)
const AppProblemasRoute = AppProblemasRouteImport.update({
  id: '/problemas',
  path: '/problemas',
  getParentRoute: () => AppRoute,
} as any)
const AppPrevisoesRoute = AppPrevisoesRouteImport.update({
  id: '/previsoes',
  path: '/previsoes',
  getParentRoute: () => AppRoute,
} as any)
const AppMudancasRoute = AppMudancasRouteImport.update({
  id: '/mudancas',
  path: '/mudancas',
  getParentRoute: () => AppRoute,
} as any)
const AppLinhagemDadosRoute = AppLinhagemDadosRouteImport.update({
  id: '/linhagem-dados',
  path: '/linhagem-dados',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentesRoute = AppIncidentesRouteImport.update({
  id: '/incidentes',
  path: '/incidentes',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDadosRoute = AppDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => AppRoute,
} as any)
const AppCorrecoesRoute = AppCorrecoesRouteImport.update({
  id: '/correcoes',
  path: '/correcoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConhecimentoRoute = AppConhecimentoRouteImport.update({
  id: '/conhecimento',
  path: '/conhecimento',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppArquiteturaRoute = AppArquiteturaRouteImport.update({
  id: '/arquitetura',
  path: '/arquitetura',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alertas': typeof AppAlertasRoute
  '/arquitetura': typeof AppArquiteturaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/conhecimento': typeof AppConhecimentoRoute
  '/correcoes': typeof AppCorrecoesRoute
  '/dados': typeof AppDadosRoute
  '/dashboard': typeof AppDashboardRoute
  '/incidentes': typeof AppIncidentesRoute
  '/linhagem-dados': typeof AppLinhagemDadosRoute
  '/mudancas': typeof AppMudancasRoute
  '/previsoes': typeof AppPrevisoesRoute
  '/problemas': typeof AppProblemasRoute
  '/qualidade-dados': typeof AppQualidadeDadosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/riscos-ola': typeof AppRiscosOlaRoute
  '/validacao': typeof AppValidacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alertas': typeof AppAlertasRoute
  '/arquitetura': typeof AppArquiteturaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/conhecimento': typeof AppConhecimentoRoute
  '/correcoes': typeof AppCorrecoesRoute
  '/dados': typeof AppDadosRoute
  '/dashboard': typeof AppDashboardRoute
  '/incidentes': typeof AppIncidentesRoute
  '/linhagem-dados': typeof AppLinhagemDadosRoute
  '/mudancas': typeof AppMudancasRoute
  '/previsoes': typeof AppPrevisoesRoute
  '/problemas': typeof AppProblemasRoute
  '/qualidade-dados': typeof AppQualidadeDadosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/riscos-ola': typeof AppRiscosOlaRoute
  '/validacao': typeof AppValidacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alertas': typeof AppAlertasRoute
  '/_app/arquitetura': typeof AppArquiteturaRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/conhecimento': typeof AppConhecimentoRoute
  '/_app/correcoes': typeof AppCorrecoesRoute
  '/_app/dados': typeof AppDadosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/incidentes': typeof AppIncidentesRoute
  '/_app/linhagem-dados': typeof AppLinhagemDadosRoute
  '/_app/mudancas': typeof AppMudancasRoute
  '/_app/previsoes': typeof AppPrevisoesRoute
  '/_app/problemas': typeof AppProblemasRoute
  '/_app/qualidade-dados': typeof AppQualidadeDadosRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/riscos-ola': typeof AppRiscosOlaRoute
  '/_app/validacao': typeof AppValidacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alertas'
    | '/arquitetura'
    | '/configuracoes'
    | '/conhecimento'
    | '/correcoes'
    | '/dados'
    | '/dashboard'
    | '/incidentes'
    | '/linhagem-dados'
    | '/mudancas'
    | '/previsoes'
    | '/problemas'
    | '/qualidade-dados'
    | '/relatorios'
    | '/riscos-ola'
    | '/validacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alertas'
    | '/arquitetura'
    | '/configuracoes'
    | '/conhecimento'
    | '/correcoes'
    | '/dados'
    | '/dashboard'
    | '/incidentes'
    | '/linhagem-dados'
    | '/mudancas'
    | '/previsoes'
    | '/problemas'
    | '/qualidade-dados'
    | '/relatorios'
    | '/riscos-ola'
    | '/validacao'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/alertas'
    | '/_app/arquitetura'
    | '/_app/configuracoes'
    | '/_app/conhecimento'
    | '/_app/correcoes'
    | '/_app/dados'
    | '/_app/dashboard'
    | '/_app/incidentes'
    | '/_app/linhagem-dados'
    | '/_app/mudancas'
    | '/_app/previsoes'
    | '/_app/problemas'
    | '/_app/qualidade-dados'
    | '/_app/relatorios'
    | '/_app/riscos-ola'
    | '/_app/validacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/validacao': {
      id: '/_app/validacao'
      path: '/validacao'
      fullPath: '/validacao'
      preLoaderRoute: typeof AppValidacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/riscos-ola': {
      id: '/_app/riscos-ola'
      path: '/riscos-ola'
      fullPath: '/riscos-ola'
      preLoaderRoute: typeof AppRiscosOlaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qualidade-dados': {
      id: '/_app/qualidade-dados'
      path: '/qualidade-dados'
      fullPath: '/qualidade-dados'
      preLoaderRoute: typeof AppQualidadeDadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/problemas': {
      id: '/_app/problemas'
      path: '/problemas'
      fullPath: '/problemas'
      preLoaderRoute: typeof AppProblemasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/previsoes': {
      id: '/_app/previsoes'
      path: '/previsoes'
      fullPath: '/previsoes'
      preLoaderRoute: typeof AppPrevisoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mudancas': {
      id: '/_app/mudancas'
      path: '/mudancas'
      fullPath: '/mudancas'
      preLoaderRoute: typeof AppMudancasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/linhagem-dados': {
      id: '/_app/linhagem-dados'
      path: '/linhagem-dados'
      fullPath: '/linhagem-dados'
      preLoaderRoute: typeof AppLinhagemDadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidentes': {
      id: '/_app/incidentes'
      path: '/incidentes'
      fullPath: '/incidentes'
      preLoaderRoute: typeof AppIncidentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dados': {
      id: '/_app/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof AppDadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/correcoes': {
      id: '/_app/correcoes'
      path: '/correcoes'
      fullPath: '/correcoes'
      preLoaderRoute: typeof AppCorrecoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conhecimento': {
      id: '/_app/conhecimento'
      path: '/conhecimento'
      fullPath: '/conhecimento'
      preLoaderRoute: typeof AppConhecimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/arquitetura': {
      id: '/_app/arquitetura'
      path: '/arquitetura'
      fullPath: '/arquitetura'
      preLoaderRoute: typeof AppArquiteturaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alertas': {
      id: '/_app/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertasRoute: typeof AppAlertasRoute
  AppArquiteturaRoute: typeof AppArquiteturaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppConhecimentoRoute: typeof AppConhecimentoRoute
  AppCorrecoesRoute: typeof AppCorrecoesRoute
  AppDadosRoute: typeof AppDadosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIncidentesRoute: typeof AppIncidentesRoute
  AppLinhagemDadosRoute: typeof AppLinhagemDadosRoute
  AppMudancasRoute: typeof AppMudancasRoute
  AppPrevisoesRoute: typeof AppPrevisoesRoute
  AppProblemasRoute: typeof AppProblemasRoute
  AppQualidadeDadosRoute: typeof AppQualidadeDadosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppRiscosOlaRoute: typeof AppRiscosOlaRoute
  AppValidacaoRoute: typeof AppValidacaoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertasRoute: AppAlertasRoute,
  AppArquiteturaRoute: AppArquiteturaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppConhecimentoRoute: AppConhecimentoRoute,
  AppCorrecoesRoute: AppCorrecoesRoute,
  AppDadosRoute: AppDadosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIncidentesRoute: AppIncidentesRoute,
  AppLinhagemDadosRoute: AppLinhagemDadosRoute,
  AppMudancasRoute: AppMudancasRoute,
  AppPrevisoesRoute: AppPrevisoesRoute,
  AppProblemasRoute: AppProblemasRoute,
  AppQualidadeDadosRoute: AppQualidadeDadosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppRiscosOlaRoute: AppRiscosOlaRoute,
  AppValidacaoRoute: AppValidacaoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
