/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApresentacaoRouteImport } from './routes/apresentacao'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppRiscosOlaRouteImport } from './routes/_app.riscos-ola'
import { Route as AppProblemasRouteImport } from './routes/_app.problemas'
import { Route as AppPrevisoesRouteImport } from './routes/_app.previsoes'
import { Route as AppIncidentesRouteImport } from './routes/_app.incidentes'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDadosRouteImport } from './routes/_app.dados'
import { Route as AppCorrecoesRouteImport } from './routes/_app.correcoes'
import { Route as AppConhecimentoRouteImport } from './routes/_app.conhecimento'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppAssistenteRouteImport } from './routes/_app.assistente'
import { Route as AppAlertasRouteImport } from './routes/_app.alertas'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacaoRoute = ApresentacaoRouteImport.update({
  id: '/apresentacao',
  path: '/apresentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppRiscosOlaRoute = AppRiscosOlaRouteImport.update({
  id: '/riscos-ola',
  path: '/riscos-ola',
  getParentRoute: () => AppRoute,
} as any)
const AppProblemasRoute = AppProblemasRouteImport.update({
  id: '/problemas',
  path: '/problemas',
  getParentRoute: () => AppRoute,
} as any)
const AppPrevisoesRoute = AppPrevisoesRouteImport.update({
  id: '/previsoes',
  path: '/previsoes',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentesRoute = AppIncidentesRouteImport.update({
  id: '/incidentes',
  path: '/incidentes',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDadosRoute = AppDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => AppRoute,
} as any)
const AppCorrecoesRoute = AppCorrecoesRouteImport.update({
  id: '/correcoes',
  path: '/correcoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConhecimentoRoute = AppConhecimentoRouteImport.update({
  id: '/conhecimento',
  path: '/conhecimento',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistenteRoute = AppAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/login': typeof LoginRoute
  '/alertas': typeof AppAlertasRoute
  '/assistente': typeof AppAssistenteRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/conhecimento': typeof AppConhecimentoRoute
  '/correcoes': typeof AppCorrecoesRoute
  '/dados': typeof AppDadosRoute
  '/dashboard': typeof AppDashboardRoute
  '/incidentes': typeof AppIncidentesRoute
  '/previsoes': typeof AppPrevisoesRoute
  '/problemas': typeof AppProblemasRoute
  '/riscos-ola': typeof AppRiscosOlaRoute
  '/usuarios': typeof AppUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/login': typeof LoginRoute
  '/alertas': typeof AppAlertasRoute
  '/assistente': typeof AppAssistenteRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/conhecimento': typeof AppConhecimentoRoute
  '/correcoes': typeof AppCorrecoesRoute
  '/dados': typeof AppDadosRoute
  '/dashboard': typeof AppDashboardRoute
  '/incidentes': typeof AppIncidentesRoute
  '/previsoes': typeof AppPrevisoesRoute
  '/problemas': typeof AppProblemasRoute
  '/riscos-ola': typeof AppRiscosOlaRoute
  '/usuarios': typeof AppUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/apresentacao': typeof ApresentacaoRoute
  '/login': typeof LoginRoute
  '/_app/alertas': typeof AppAlertasRoute
  '/_app/assistente': typeof AppAssistenteRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/conhecimento': typeof AppConhecimentoRoute
  '/_app/correcoes': typeof AppCorrecoesRoute
  '/_app/dados': typeof AppDadosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/incidentes': typeof AppIncidentesRoute
  '/_app/previsoes': typeof AppPrevisoesRoute
  '/_app/problemas': typeof AppProblemasRoute
  '/_app/riscos-ola': typeof AppRiscosOlaRoute
  '/_app/usuarios': typeof AppUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apresentacao'
    | '/login'
    | '/alertas'
    | '/assistente'
    | '/configuracoes'
    | '/conhecimento'
    | '/correcoes'
    | '/dados'
    | '/dashboard'
    | '/incidentes'
    | '/previsoes'
    | '/problemas'
    | '/riscos-ola'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apresentacao'
    | '/login'
    | '/alertas'
    | '/assistente'
    | '/configuracoes'
    | '/conhecimento'
    | '/correcoes'
    | '/dados'
    | '/dashboard'
    | '/incidentes'
    | '/previsoes'
    | '/problemas'
    | '/riscos-ola'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/apresentacao'
    | '/login'
    | '/_app/alertas'
    | '/_app/assistente'
    | '/_app/configuracoes'
    | '/_app/conhecimento'
    | '/_app/correcoes'
    | '/_app/dados'
    | '/_app/dashboard'
    | '/_app/incidentes'
    | '/_app/previsoes'
    | '/_app/problemas'
    | '/_app/riscos-ola'
    | '/_app/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApresentacaoRoute: typeof ApresentacaoRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacao': {
      id: '/apresentacao'
      path: '/apresentacao'
      fullPath: '/apresentacao'
      preLoaderRoute: typeof ApresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/riscos-ola': {
      id: '/_app/riscos-ola'
      path: '/riscos-ola'
      fullPath: '/riscos-ola'
      preLoaderRoute: typeof AppRiscosOlaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/problemas': {
      id: '/_app/problemas'
      path: '/problemas'
      fullPath: '/problemas'
      preLoaderRoute: typeof AppProblemasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/previsoes': {
      id: '/_app/previsoes'
      path: '/previsoes'
      fullPath: '/previsoes'
      preLoaderRoute: typeof AppPrevisoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidentes': {
      id: '/_app/incidentes'
      path: '/incidentes'
      fullPath: '/incidentes'
      preLoaderRoute: typeof AppIncidentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dados': {
      id: '/_app/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof AppDadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/correcoes': {
      id: '/_app/correcoes'
      path: '/correcoes'
      fullPath: '/correcoes'
      preLoaderRoute: typeof AppCorrecoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conhecimento': {
      id: '/_app/conhecimento'
      path: '/conhecimento'
      fullPath: '/conhecimento'
      preLoaderRoute: typeof AppConhecimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistente': {
      id: '/_app/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AppAssistenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alertas': {
      id: '/_app/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertasRoute: typeof AppAlertasRoute
  AppAssistenteRoute: typeof AppAssistenteRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppConhecimentoRoute: typeof AppConhecimentoRoute
  AppCorrecoesRoute: typeof AppCorrecoesRoute
  AppDadosRoute: typeof AppDadosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIncidentesRoute: typeof AppIncidentesRoute
  AppPrevisoesRoute: typeof AppPrevisoesRoute
  AppProblemasRoute: typeof AppProblemasRoute
  AppRiscosOlaRoute: typeof AppRiscosOlaRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertasRoute: AppAlertasRoute,
  AppAssistenteRoute: AppAssistenteRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppConhecimentoRoute: AppConhecimentoRoute,
  AppCorrecoesRoute: AppCorrecoesRoute,
  AppDadosRoute: AppDadosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIncidentesRoute: AppIncidentesRoute,
  AppPrevisoesRoute: AppPrevisoesRoute,
  AppProblemasRoute: AppProblemasRoute,
  AppRiscosOlaRoute: AppRiscosOlaRoute,
  AppUsuariosRoute: AppUsuariosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApresentacaoRoute: ApresentacaoRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
